use_frameworks!
platform :ios, '10.0'

target 'ABVideoRangeSlider_Example' do
  pod 'ABVideoRangeSlider', :path => '../'

  target 'ABVideoRangeSlider_Tests' do
    inherit! :search_paths

    
  end
end
